# 'brew tap'
tap "homebrew/bundle"

# 'brew tap' with custom Git URL
# e.g tap "user/tap-repo", "https://user@bitbucket.org/user/homebrew-tap-repo.git"

# set arguments for all 'brew install --cask' commands
cask_args appdir: "~/Applications", require_sha: true

# 'brew install'
brew "ack"
brew "awscli"
brew "bat"
brew "commitizen"
brew "exercism"
brew "fd"
brew "fzf"
brew "gh"
brew "git-cola"
brew "git-crypt"
brew "gitmoji"
brew "glow"
brew "gnupg"
brew "go"
brew "helix"
brew "helm"
brew "k9s"
brew "kube-linter"
brew "kubernetes-cli"
brew "lazygit"
brew "lua-language-server"
brew "luarocks"
brew "mas"
brew "neovim"
brew "ninja"
brew "operator-sdk"
brew "ranger"
brew "ripgrep"
brew "starship"
brew "staticcheck"
brew "stern"
brew "stylua"
brew "themekit"
brew "tig"
brew "tmux"
brew "tree"
brew "watch"
brew "yarn"
brew "yq"
brew "zk" # Zettelkasten CLI tool

# 'brew install --cask'
cask "fly"
cask "gpg-suite"
cask "obsidian"
cask "visual-studio-code"

# 'mas install'
#mas "1Password", id: 443987910

# 'whalebrew install'
#whalebrew "whalebrew/wget"
