[keybindings]
"Shift+i" = "seek +10000"
"j" = "move down 1"
"k" = "move up 1"
"Ctrl+d" = "move down 5"
"Ctrl+u" = "move up 5"
"gg" = "move top"
"G" = "move bottom"


[theme]
background = "black"
primary = "light white"
secondary = "light black"
title = "green"
playing = "green"
playing_selected = "light green"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "light white"
cmdline_bg = "black"
